name: production workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Post a message in a channel
        uses: slackapi/slack-github-action@v3.0.3
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Staging Pipeline wurde gestartet von ${{github.actor}}. Pipeline : ${{github.workflow}}"

      - name: checkout
        uses: actions/checkout@v6

      - name: ssh setup
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY_PROD}}" > ~/.ssh/deploy_key_prod
          chmod 400 ~/.ssh/deploy_key_prod
          for ip in ${{secrets.EC2_IPS_PROD}}; do
          ssh-keyscan -H $ip  >> ~/.ssh/known_hosts
          done


      - name: install nginx
        run: |
          for ip in ${{secrets.EC2_IPS_PROD}}; do
          # only run install for nginx if update successful
          ssh -i ~/.ssh/deploy_key_prod ubuntu@$ip "sudo apt update && sudo apt install nginx -y"
          done

      - name: deploy website
        run: |
          for ip in ${{secrets.EC2_IPS_PROD}}; do
          scp -i ~/.ssh/deploy_key_prod frontend/index.html ubuntu@$ip:/home/ubuntu/index.html
          ssh -i ~/.ssh/deploy_key_prod ubuntu@$ip "sudo cp /home/ubuntu/index.html /var/www/html/index.html"
          done

      - name: Post a message in a channel bei Erfolg
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v3.0.3
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Prod Deployment erfolgreich !"
      # Again this would also try to send a slack message if the previous step fails
      - name: Post a message in a channel bei Fehlschlag
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v3.0.3
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Prod Deployment nicht erfolgreich !!!"
